apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: NodePort
  externalIPs:
  - 9.30.249.171
  ports:
  - port : 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: hello-world
