#Create a Service
apiVersion: v1
kind: Service
metadata:
  name: my-emp1
  labels:
    run: my-emp1
spec:
  type: NodePort
  externalIPs:
  - 9.30.249.171
  ports:
  - port : 80
    targetPort: 8888
    protocol: TCP
  selector:
    run: my-emp1
