#create deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-emp1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-emp1
    spec:
      containers:
      - name: my-emp1
        image: kavisuresh/employee1
        ports:
        - containerPort: 8888
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
